# Dependencies
markdown:         kramdown
highlighter:      rouge
include:          ['_pages']

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Introduction to Latin 1
tagline:          'LATN 101'
course_number:    'LATN 101'
semester:         'Fall 2019'
location:         'College of the Holy Cross'
url:              https://dlibatique.github.io/LATN101-F19
baseurl:          /

author:
  name:           'Daniel Libatique'
  url:            https://dlibatique.github.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/LATN101-F19
